"""
bosonic-dla-finiteness: dimensional classification of bosonic Hamiltonian Lie
algebras.

The entry point is check_finiteness, which classifies the DLA generated by a
set of BosonicGenerator basis elements against a set of FreeHamiltonian drifts
as finite-dimensional, provably infinite-dimensional, or inconclusive.

Definitions follow arXiv:2511.06940, arXiv:2401.00069.
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("bosonic-dla-finiteness")
except PackageNotFoundError:  # pragma: no cover - source tree without install
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
